[package]
name = "record_datagrams"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "record_datagrams"
path = "src/main.rs"

[dependencies]
serde_json = { workspace = true }
clap = { workspace = true }
libc = { workspace = true }
datagram = { path = "../../capability/datagram" }
write_engine = { path = "../../capability/write_engine" }
