[package]
name = "traffic_interceptor_rewriter"
version = "0.1.0"
edition = "2021"

[lib]
name = "traffic_interceptor_rewriter"
crate-type = ["cdylib", "rlib"]

[dependencies]
serde_json = { workspace = true }
pyo3 = { workspace = true }
compaction_inject_core = { path = "../../core/compaction_inject_core" }
schema_core = { path = "../../core/schema_core" }
intercept_core = { path = "../../core/intercept_core" }
session_io = { path = "../../capability/session_io" }
