//! QA report reading, grouping, and formatting.
//!
//! Reads .qa sidecar files (generated by saga), groups issues by check name,
//! and formats output through pluggable formatters.
//!
//! Formatters:
//!   - PlainFormatter: grouped text for LLM context injection
//!   - ColoredFormatter: ANSI terminal output for humans
//!   - JsonFormatter: re-grouped JSON for machines

use serde::Deserialize;
use std::collections::BTreeMap;

// =============================================================================
// Data structures — deserialized from .qa JSON
// =============================================================================

/// A single issue from a .qa sidecar file.
#[derive(Debug, Clone, Deserialize)]
pub struct Issue {
    pub tool: String,
    pub code: String,
    pub severity: String,
    pub line: usize,
    #[serde(default)]
    pub column: Option<usize>,
    #[serde(default)]
    pub message: String,
    #[serde(default)]
    pub category: String,
    #[serde(default)]
    pub fixable: bool,
    // Gleipnir educational fields
    #[serde(default)]
    pub signal: String,
    #[serde(default)]
    pub direction: String,
    #[serde(default)]
    pub canary: String,
}

/// A .qa sidecar report for one file.
#[derive(Debug, Deserialize)]
pub struct SanityReport {
    pub file: String,
    #[serde(default)]
    pub relative_path: String,
    #[serde(default)]
    pub issues: Vec<Issue>,
}

// =============================================================================
// Grouped structures — intermediate representation for formatters
// =============================================================================

/// A single issue with its file context attached.
#[derive(Debug, Clone)]
pub struct LocatedIssue {
    pub file: String,
    pub line: usize,
    pub message: String,
}

/// A group of issues sharing the same check code.
#[derive(Debug)]
pub struct CheckGroup {
    pub tool: String,
    pub code: String,
    pub severity: String,
    pub signal: String,
    pub direction: String,
    pub canary: String,
    pub issues: Vec<LocatedIssue>,
    pub file_count: usize,
}

// =============================================================================
// Grouping — .qa issues → CheckGroups
// =============================================================================

/// Group issues by (tool, code), preserving encounter order.
///
/// Uses the first issue in each group as the representative for
/// educational fields (signal, direction, canary).
pub fn group_issues(reports: &[SanityReport]) -> Vec<CheckGroup> {
    // BTreeMap for deterministic ordering by key
    let mut groups: BTreeMap<(String, String), (Issue, Vec<LocatedIssue>)> = BTreeMap::new();

    for report in reports {
        for issue in &report.issues {
            let key = (issue.tool.clone(), issue.code.clone());
            let located = LocatedIssue {
                file: report.relative_path.clone(),
                line: issue.line,
                message: issue.message.clone(),
            };

            groups
                .entry(key)
                .or_insert_with(|| (issue.clone(), Vec::new()))
                .1
                .push(located);
        }
    }

    groups
        .into_iter()
        .map(|((tool, code), (representative, issues))| {
            let file_count = {
                let mut files: Vec<&str> = issues.iter().map(|li| li.file.as_str()).collect();
                files.sort();
                files.dedup();
                files.len()
            };
            CheckGroup {
                tool,
                code,
                severity: representative.severity,
                signal: representative.signal,
                direction: representative.direction,
                canary: representative.canary,
                issues,
                file_count,
            }
        })
        .collect()
}

/// Count total issues across all groups.
pub fn total_issues(groups: &[CheckGroup]) -> usize {
    groups.iter().map(|g| g.issues.len()).sum()
}

// =============================================================================
// Formatter trait
// =============================================================================

/// Pluggable output formatter for grouped QA results.
pub trait QaFormatter {
    fn format(&self, groups: &[CheckGroup]) -> String;
}

// =============================================================================
// Text wrapping
// =============================================================================

const MAX_WIDTH: usize = 79;

/// Break text into lines that fit within `width` visible characters.
/// Returns raw text lines — caller adds formatting/prefix.
fn wrap_lines(text: &str, width: usize) -> Vec<String> {
    if width == 0 {
        return vec![text.to_string()];
    }

    let mut lines: Vec<String> = Vec::new();
    let mut current = String::new();

    for word in text.split_whitespace() {
        if current.is_empty() {
            current = word.to_string();
        } else if current.len() + 1 + word.len() > width {
            lines.push(current);
            current = word.to_string();
        } else {
            current.push(' ');
            current.push_str(word);
        }
    }
    if !current.is_empty() {
        lines.push(current);
    }
    if lines.is_empty() {
        lines.push(String::new());
    }

    lines
}

/// Break text with different first-line and continuation widths.
/// First line accounts for label prefix, continuation lines get more room.
fn wrap_adaptive(text: &str, first_width: usize, rest_width: usize) -> Vec<String> {
    let mut lines: Vec<String> = Vec::new();
    let mut current = String::new();
    let mut width = first_width;

    for word in text.split_whitespace() {
        if current.is_empty() {
            current = word.to_string();
        } else if current.len() + 1 + word.len() > width {
            lines.push(current);
            current = word.to_string();
            width = rest_width;
        } else {
            current.push(' ');
            current.push_str(word);
        }
    }
    if !current.is_empty() {
        lines.push(current);
    }
    if lines.is_empty() {
        lines.push(String::new());
    }

    lines
}

/// Wrap text to fit within MAX_WIDTH, prepending indent to each line.
/// For plain text where indent string length equals visible prefix width.
fn wrap_text(text: &str, indent: &str) -> String {
    let usable = MAX_WIDTH.saturating_sub(indent.len());
    let lines = wrap_lines(text, usable);
    lines
        .iter()
        .map(|line| format!("{indent}{line}"))
        .collect::<Vec<_>>()
        .join("\n")
}

// =============================================================================
// Filtering
// =============================================================================

/// Filter groups to only include a specific tool.
pub fn filter_by_tool(groups: Vec<CheckGroup>, tool: &str) -> Vec<CheckGroup> {
    groups.into_iter().filter(|g| g.tool == tool).collect()
}

// =============================================================================
// PlainFormatter — LLM context injection
// =============================================================================

pub struct PlainFormatter;

impl QaFormatter for PlainFormatter {
    fn format(&self, groups: &[CheckGroup]) -> String {
        if groups.is_empty() {
            return "All checks passed.".to_string();
        }

        let total = total_issues(groups);
        let mut sections: Vec<String> = Vec::new();

        sections.push(format!(
            "GLEIPNIR: {} violations across {} check types",
            total,
            groups.len()
        ));
        sections.push(String::new());

        for group in groups {
            let files_word = if group.file_count == 1 { "file" } else { "files" };
            sections.push(format!(
                "{} ({}) — {} violations across {} {}",
                group.code, group.severity, group.issues.len(), group.file_count, files_word
            ));

            if !group.signal.is_empty() {
                sections.push(wrap_text(&format!("Signal: {}", group.signal), "  "));
            }
            if !group.direction.is_empty() {
                sections.push(wrap_text(&format!("Direction: {}", group.direction), "  "));
            }
            if !group.canary.is_empty() {
                sections.push(wrap_text(&format!("Canary: {}", group.canary), "  "));
            }
            sections.push(String::new());

            for issue in &group.issues {
                sections.push(format!("  {}:{}", issue.file, issue.line));
            }
            sections.push(String::new());
        }

        sections.join("\n").trim_end().to_string()
    }
}

// =============================================================================
// ColoredFormatter — ANSI terminal for humans
// =============================================================================

pub struct ColoredFormatter;

// ANSI escape sequences
const RESET: &str = "\x1b[0m";
const BOLD: &str = "\x1b[1m";
const DIM: &str = "\x1b[2m";
const RED: &str = "\x1b[31m";
const YELLOW: &str = "\x1b[33m";
const CYAN: &str = "\x1b[36m";
const WHITE: &str = "\x1b[37m";
const BG_RED: &str = "\x1b[41m";

fn severity_color(severity: &str) -> &'static str {
    match severity {
        "error" | "blocked" => "\x1b[1;31m",  // bold red
        "warning" => "\x1b[1;33m",             // bold yellow
        _ => "\x1b[1;37m",                     // bold white
    }
}

impl QaFormatter for ColoredFormatter {
    fn format(&self, groups: &[CheckGroup]) -> String {
        if groups.is_empty() {
            return format!(
                "\n{BOLD}{CYAN}{bar}{RESET}\n  GLEIPNIR: All checks passed.\n{BOLD}{CYAN}{bar}{RESET}",
                bar = "━".repeat(MAX_WIDTH),
            );
        }

        let total = total_issues(groups);
        let mut sections: Vec<String> = Vec::new();

        // Banner
        let bar = "━".repeat(MAX_WIDTH);
        sections.push(format!("\n{BOLD}{RED}{bar}{RESET}"));
        sections.push(format!(
            "{BOLD}{WHITE}{BG_RED}  GLEIPNIR  {RESET}  {BOLD}{WHITE}{total} violations{RESET} across {BOLD}{WHITE}{count} check types{RESET}",
            count = groups.len(),
        ));
        sections.push(format!("{BOLD}{RED}{bar}{RESET}"));

        for group in groups {
            let color = severity_color(&group.severity);
            let files_word = if group.file_count == 1 { "file" } else { "files" };

            // Group header
            sections.push(format!(
                "\n{color}┌─ {code}{RESET}  {DIM}{severity}{RESET}  {BOLD}{WHITE}{count}{RESET} in {file_count} {files_word}",
                code = group.code,
                severity = group.severity,
                count = group.issues.len(),
                file_count = group.file_count,
            ));
            sections.push(format!("{color}│{RESET}"));

            // Educational content — wrap with correct visible widths
            // Visible prefixes:
            //   gutter:       "│  "     = 3 chars
            //   continuation: "│    "   = 5 chars
            //   first line:   "│  Label: " = 3 + label.len() + 2
            let gutter = format!("{color}│{RESET}  ");
            let continuation = format!("{color}│{RESET}    ");
            let cont_width = MAX_WIDTH - 5; // continuation text width

            if !group.signal.is_empty() {
                // "│  Signal: " = 11 visible chars
                let lines = wrap_adaptive(&group.signal, MAX_WIDTH - 11, cont_width);
                sections.push(format!("{gutter}{BOLD}{CYAN}Signal:{RESET} {}", lines[0]));
                for line in &lines[1..] {
                    sections.push(format!("{continuation}{line}"));
                }
            }
            if !group.direction.is_empty() {
                // "│  Direction: " = 14 visible chars
                let lines = wrap_adaptive(&group.direction, MAX_WIDTH - 14, cont_width);
                sections.push(format!("{gutter}{BOLD}{CYAN}Direction:{RESET} {}", lines[0]));
                for line in &lines[1..] {
                    sections.push(format!("{continuation}{line}"));
                }
            }
            if !group.canary.is_empty() {
                // "│  Canary: " = 11 visible chars
                let lines = wrap_adaptive(&group.canary, MAX_WIDTH - 11, cont_width);
                sections.push(format!("{gutter}{BOLD}{YELLOW}Canary:{RESET} {}", lines[0]));
                for line in &lines[1..] {
                    sections.push(format!("{continuation}{line}"));
                }
            }

            // Locations
            sections.push(format!("{color}│{RESET}"));
            for issue in &group.issues {
                sections.push(format!(
                    "{color}│{RESET}  {DIM}{file}:{line}{RESET}",
                    file = issue.file,
                    line = issue.line,
                ));
            }
            sections.push(format!("{color}└{bar}{RESET}", bar = "─".repeat(MAX_WIDTH - 1)));
        }

        sections.join("\n")
    }
}

// =============================================================================
// JsonFormatter — machine-readable re-grouped output
// =============================================================================

pub struct JsonFormatter;

impl QaFormatter for JsonFormatter {
    fn format(&self, groups: &[CheckGroup]) -> String {
        let json_groups: Vec<serde_json::Value> = groups
            .iter()
            .map(|group| {
                let locations: Vec<serde_json::Value> = group
                    .issues
                    .iter()
                    .map(|li| {
                        serde_json::json!({
                            "file": li.file,
                            "line": li.line,
                            "message": li.message,
                        })
                    })
                    .collect();

                serde_json::json!({
                    "tool": group.tool,
                    "code": group.code,
                    "severity": group.severity,
                    "count": group.issues.len(),
                    "file_count": group.file_count,
                    "signal": group.signal,
                    "direction": group.direction,
                    "canary": group.canary,
                    "locations": locations,
                })
            })
            .collect();

        let output = serde_json::json!({
            "total": total_issues(groups),
            "check_types": groups.len(),
            "groups": json_groups,
        });

        serde_json::to_string_pretty(&output).unwrap_or_default()
    }
}

// =============================================================================
// Tests
// =============================================================================

#[cfg(test)]
mod tests {
    use super::*;

    fn sample_report() -> SanityReport {
        SanityReport {
            file: "/project/src/helpers.py".to_string(),
            relative_path: "src/helpers.py".to_string(),
            issues: vec![
                Issue {
                    tool: "gleipnir".to_string(),
                    code: "no_raise_in_pure".to_string(),
                    severity: "error".to_string(),
                    line: 45,
                    column: None,
                    message: "Exception raised in pure function.".to_string(),
                    category: "structure".to_string(),
                    fixable: false,
                    signal: "Raising is a side effect.".to_string(),
                    direction: "Return a typed error.".to_string(),
                    canary: "LLM reached for exceptions.".to_string(),
                },
                Issue {
                    tool: "gleipnir".to_string(),
                    code: "no_raise_in_pure".to_string(),
                    severity: "error".to_string(),
                    line: 62,
                    column: None,
                    message: "Exception raised in pure function.".to_string(),
                    category: "structure".to_string(),
                    fixable: false,
                    signal: "Raising is a side effect.".to_string(),
                    direction: "Return a typed error.".to_string(),
                    canary: "LLM reached for exceptions.".to_string(),
                },
                Issue {
                    tool: "ruff".to_string(),
                    code: "E501".to_string(),
                    severity: "warning".to_string(),
                    line: 80,
                    column: Some(101),
                    message: "Line too long (108 > 100)".to_string(),
                    category: "style".to_string(),
                    fixable: false,
                    signal: String::new(),
                    direction: String::new(),
                    canary: String::new(),
                },
            ],
        }
    }

    fn sample_report_2() -> SanityReport {
        SanityReport {
            file: "/project/src/loader.py".to_string(),
            relative_path: "src/loader.py".to_string(),
            issues: vec![Issue {
                tool: "gleipnir".to_string(),
                code: "no_raise_in_pure".to_string(),
                severity: "error".to_string(),
                line: 18,
                column: None,
                message: "Exception raised in pure function.".to_string(),
                category: "structure".to_string(),
                fixable: false,
                signal: "Raising is a side effect.".to_string(),
                direction: "Return a typed error.".to_string(),
                canary: "LLM reached for exceptions.".to_string(),
            }],
        }
    }

    #[test]
    fn test_group_issues_clusters_by_code() {
        let reports = vec![sample_report(), sample_report_2()];
        let groups = group_issues(&reports);

        // Two distinct (tool, code) pairs: gleipnir/no_raise_in_pure and ruff/E501
        assert_eq!(groups.len(), 2);
    }

    #[test]
    fn test_group_issues_counts() {
        let reports = vec![sample_report(), sample_report_2()];
        let groups = group_issues(&reports);

        let gleipnir_group = groups.iter().find(|g| g.code == "no_raise_in_pure").unwrap();
        assert_eq!(gleipnir_group.issues.len(), 3);
        assert_eq!(gleipnir_group.file_count, 2);

        let ruff_group = groups.iter().find(|g| g.code == "E501").unwrap();
        assert_eq!(ruff_group.issues.len(), 1);
        assert_eq!(ruff_group.file_count, 1);
    }

    #[test]
    fn test_group_issues_preserves_educational_fields() {
        let reports = vec![sample_report()];
        let groups = group_issues(&reports);

        let gleipnir_group = groups.iter().find(|g| g.code == "no_raise_in_pure").unwrap();
        assert_eq!(gleipnir_group.signal, "Raising is a side effect.");
        assert_eq!(gleipnir_group.direction, "Return a typed error.");
        assert_eq!(gleipnir_group.canary, "LLM reached for exceptions.");
    }

    #[test]
    fn test_plain_formatter_empty() {
        let formatter = PlainFormatter;
        assert_eq!(formatter.format(&[]), "All checks passed.");
    }

    #[test]
    fn test_plain_formatter_grouped_output() {
        let reports = vec![sample_report(), sample_report_2()];
        let groups = group_issues(&reports);
        let formatter = PlainFormatter;
        let output = formatter.format(&groups);

        assert!(output.contains("GLEIPNIR: 4 violations across 2 check types"));
        assert!(output.contains("no_raise_in_pure (error)"));
        assert!(output.contains("Signal: Raising is a side effect."));
        assert!(output.contains("src/helpers.py:45"));
        assert!(output.contains("src/loader.py:18"));
        // Signal appears only once per group
        assert_eq!(output.matches("Signal: Raising is a side effect.").count(), 1);
    }

    #[test]
    fn test_colored_formatter_has_ansi() {
        let reports = vec![sample_report()];
        let groups = group_issues(&reports);
        let formatter = ColoredFormatter;
        let output = formatter.format(&groups);

        assert!(output.contains("\x1b["));
        assert!(output.contains("GLEIPNIR"));
    }

    #[test]
    fn test_json_formatter_structure() {
        let reports = vec![sample_report(), sample_report_2()];
        let groups = group_issues(&reports);
        let formatter = JsonFormatter;
        let output = formatter.format(&groups);

        let parsed: serde_json::Value = serde_json::from_str(&output).unwrap();
        assert_eq!(parsed["total"], 4);
        assert_eq!(parsed["check_types"], 2);
        assert!(parsed["groups"].is_array());
    }

    #[test]
    fn test_filter_by_tool() {
        let reports = vec![sample_report()];
        let groups = group_issues(&reports);

        let gleipnir_only = filter_by_tool(groups, "gleipnir");
        assert_eq!(gleipnir_only.len(), 1);
        assert_eq!(gleipnir_only[0].tool, "gleipnir");
    }

    #[test]
    fn test_total_issues() {
        let reports = vec![sample_report(), sample_report_2()];
        let groups = group_issues(&reports);
        assert_eq!(total_issues(&groups), 4);
    }
}
