[package]
name = "gate_universal_format_input"
version = "0.1.0"
edition = "2021"

[lib]
name = "gate_universal_format_input"
crate-type = ["cdylib", "rlib"]

[dependencies]
pyo3 = { workspace = true }
schemas_embedded = { path = "../../capability/schemas_embedded" }
gate_io = { path = "../../capability/gate_io" }
