[package]
name = "default_apply_io"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["rlib"]

[dependencies]
serde_json = { workspace = true }
default_apply_core = { path = "../../core/default_apply_core" }
format_core = { path = "../../core/format_core" }
schema_core = { path = "../../core/schema_core" }
error_core = { path = "../../core/error_core" }
